### ISSUE TITLE
Silktouch 2

### ISSUE THREAD

**Issue by tristiisch** [Dragorn421/ItemBasedCommandBlocker#1]
Bonjours, peux on bloquer seulement silktouch 2 et laisse silktouch 1 ?

**Comment by Dragorn421** [comment]
On ne pouvait pas jusqu'à maintenant, merci de ton retour.  
Voici donc comment faire **_dans la dernière version du plugin_** (à télécharger au même endroit) :  

``` yaml
filters:
  a:
    command: /repair#par exemple /repair
    comparison-type: equals
    type: DIAMOND_PICKAXE
    data: -1
    with-enchantments:
    # Ajouter le :2 permet de cibler un enchantement de niveau 2, ne rien mettre permet de cibler tous les niveaux
    - SILK_TOUCH:2
    without-enchantments: []
```

J'en profite pour te rappeler qu'il faut aussi dupliquer la section et faire commencer la copie par :  

``` yaml
  b:
    command: '/repair '#espace très important
    comparison-type: startsWith
```

Sinon le plugin bloquera correctement `/repair` mais pas `/repair efrzf` (dans le deuxième cas le plugin de repair exécutera quand même le repair).
